ApiUsageError: use correct type as defined in Exceptions
ApiUsageError derives from ProgrammingError and is meant to indicate a
programming error in the code that calls an api.  This will result in a
400 because the error is on the client side.

ApiUsageError is meant to be used when the contract of the API is
violated and as such, it is not a SemanticException.

The extra ApiUsageError defined here was removed and the handling of it
was added in the ProgrammingErrorExceptionHandler.